version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: restore npm cache
          keys:
            - npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run setup
      - run: npm run test
      - run: npm run coverage
      - save_cache:
          name: save npm cache
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
