// Generated by LiveScript 1.4.0
(function(){
  var diffJson;
  diffJson = function(expected, actual, done){
    var changes, i$, len$, part, color;
    changes = diff.diffJson(expected, actual);
    if (changes.length === 1) {
      return done();
    } else {
      console.log(red('\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'));
      console.log(red('Mismatching call records!\n'));
      for (i$ = 0, len$ = changes.length; i$ < len$; ++i$) {
        part = changes[i$];
        color = (fn$());
        process.stdout.write(color(part.value));
      }
      return console.log(red('\n\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n'));
    }
    function fn$(){
      switch (false) {
      case !part.added:
        return green;
      case !part.removed:
        return red;
      default:
        return grey;
      }
    }
  };
}).call(this);
