name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "22"
      - run: npm run setup
      - run: npm run test
      - run: npm run fix
      - name: Indicate formatting issues
        run: git diff HEAD --exit-code --color
      - run: npm run coverage
      - uses: coverallsapp/github-action@v2
